In [2]:
import numpy as np

In [4]:
arr = np.array([10, 20, 30, 40])
print(arr, type(arr))

[10 20 30 40] <class 'numpy.ndarray'>


In [ ]:
# python list vs NumPy array : 

#1. NumPy arraya are faster(optimized in c)
#2. NumPy stores data in continous memory blocks
#3. uses less memory(optimized storage)
#4. built-in  mathametical functions
#5. supports direct vectorized operations

In [ ]:
# so why is NumPy is faster ?

#. Homogeneous data types and contigous memory
#. vector operations & c implementations
#. Reduce overhead

In [6]:
# we can even print the shape total number of elements :

print(arr.shape)

(4,)


In [12]:
# 2D array

arr2D = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr2, arr2D.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]] (3, 3)


In [25]:
#create 

arr1 = np.zeros((2, 3), dtype = "int64") #prefill
print(arr1, arr1.shape)


arr2 = np.ones((3, 3), dtype="int64")
print(arr2, arr2.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)


In [28]:
arr3 = np.full((3, 2), 100)
print(arr3, arr3.shape) #prefill with values

[[100 100]
 [100 100]
 [100 100]] (3, 2)
